ewlu/gcc-precommit-ci

.github/workflows/run_checks.yaml
=> fix markdown code block

.github/workflows/build-target.yaml, .github/workflows/test-regression.yaml
use peter-evans create an issue to update issues to fix duplicate issue creation during build. peter-evans create an issue uses an issue number for updates #286
=> change update issue action

.github/workflows/generate-precommit-summary.yaml, .github/workflows/run_checks.yaml, .github/workflows/test-regression.yaml
add second chance for build in case of secondary rate limits.
=> fix typo in compare. change apply to use jason-evans create issue 

.github/workflows/build-target.yaml, .github/workflows/generate-precommit-summary.yaml, .github/workflows/init-submodules.yaml, .github/workflows/patchworks.yaml, .github/workflows/run_checks.yaml, .github/workflows/test-regression.yaml
Check the commits individually to see easily-digestible changes. Feel free to tell me you accept certain commits and I'll cherry pick them to the main branch.
=> Various refactors

.github/workflows/build-target.yaml, .github/workflows/generate-precommit-summary.yaml, .github/workflows/lint.yaml, .github/workflows/run_checks.yaml, .github/workflows/test-regression.yaml
depends on https://github.com/patrick-rivos/riscv-gnu-toolchain/pull/440
=> refactor to use one issue with issue comments for reporting

.github/workflows/build-target.yaml
Fixes https://github.com/ewlu/gcc-precommit-ci/actions/runs/6585434808/job/17892799145#step:9:74
=> Download patches artifact to fix missing patch info in reporting to patchwork

.github/workflows/build-target.yaml, .github/workflows/generate-precommit-summary.yaml, .github/workflows/lint.yaml, .github/workflows/run_checks.yaml, .github/workflows/test-regression.yaml
The initial comment uses #issue-{commentid}. All subsequent comments use #issuecomment-{commentid}
=> Use #issuecomment for all links except additional info

.github/actions/common/build-target/action.yaml, .github/workflows/test-regression.yaml
=> move build into subaction

.github/actions/common/restore-stage-2/action.yaml, .github/actions/common/run-testsuite/action.yaml, .github/workflows/test-regression.yaml
=> move testsuite into subaction

.github/actions/extract-apply-patches-trunk-or-baseline/action.yaml, .github/workflows/test-regression.yaml
=> move download/extract/apply patches to subaction

.github/workflows/run-checks.yaml
This reverts commit f578b6b4fccd51cf102504034d139db76009da72.
=> Revert "Output failed hunks for fails-to-apply (#527)"

.github/actions/download-all-comparison-artifacts/action.yaml, .github/workflows/build-target.yaml, .github/workflows/run-checks.yaml, .github/workflows/test-regression.yaml
https://github.com/ewlu/gcc-precommit-ci/issues/614
=> add newlib rv64gcv support

.github/actions/common/build-target/action.yaml, .github/actions/common/restore-stage-2/action.yaml, .github/actions/common/run-testsuite/action.yaml
Same as https://github.com/patrick-rivos/gcc-postcommit-ci/pull/147
=> Fix minor issues in common actions

.github/workflows/generate-precommit-summary.yaml, .github/workflows/test-regression.yaml, test/allowlist/README.md, test/allowlist/gcc/glibc.log
Merge only after we have sum files on postcommit
=> add new lenient allowlist and consume sum files

test/allowlist/gcc/glibc.log, test/allowlist/gcc/glibc.rv32.v.log, test/allowlist/gcc/newlib.rv64.v.log
Also add a fail to the allowlist.
=> Constrain allowlist to specific targets

.github/workflows/lint.yaml
reference: https://github.com/patrick-rivos/riscv-gnu-toolchain/blob/build-frequent/scripts/download_patches.sh#L24
=> update patch name in check

test/allowlist/gcc/common.log
Merge after a few postcommit runs complete
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113009
=> rm flakey failures from allowlist with PR113009 fix

.github/actions/common/build-target/action.yaml, .github/actions/common/run-testsuite/action.yaml, .github/workflows/test-regression.yaml, test/allowlist/gcc/glibc.log
following https://github.com/patrick-rivos/gcc-postcommit-ci/commit/3f72fb67c27439afacf3eb87bcc52a280bb3a56f for core limiting
=> add to tsvc test execution timeouts to allowlist and limit core usage

.github/workflows/generate-precommit-summary.yaml, .github/workflows/init-submodules.yaml
glibc: 2.37 --> 2.39
binutils: 2.41 --> 2.42
gdb: 12.1 --> 14.1
llvm: 16.0.5 --> 17.0.2
=> bump submodules

.github/actions/download-all-comparison-artifacts/action.yaml, .github/workflows/generate-precommit-summary.yaml, .github/workflows/run-checks.yaml, configure-scripts/rv32imc_zba_zbb_zbc_zbs-ilp32d
To help catch situations where patches that pass precommit break postcommit
* postcommit: https://github.com/patrick-rivos/gcc-postcommit-ci/issues/938 
* precommit: https://github.com/ewlu/gcc-precommit-ci/issues/1533#issuecomment-2111796928
=> add rv32imc_zba_zbb_zbc_zbs-ilp32 target

.github/workflows/run-checks.yaml
Wait for a clean staging run before merging.
=> Bump riscv-gnu-toolchain for git apply log and linter update

.github/workflows/patchworks.yaml, .github/workflows/run-checks.yaml, .github/workflows/staging.yaml
https://github.com/orgs/community/discussions/27154#discussioncomment-3254845
=> link staging issue to original issue

.github/actions/extract-apply-patches-trunk-or-baseline/action.yaml, .github/workflows/run-checks.yaml, .github/workflows/test-regression.yaml
fixes https://github.com/ewlu/gcc-precommit-ci/issues/1985#issuecomment-2260923540
=> keep baseline when building build only targets when running testsuite

test/allowlist/gcc/glibc.log
=> remove fixed fortran testcase

.github/workflows/generate-precommit-summary.yaml
Use the same process as post-commit for uploading comment gists.
=> Upload gist for trimmed summaries

.github/actions/report-build-complete-status/action.yaml, .github/workflows/staging.yaml, .github/workflows/test-regression.yaml
manual run with build-failure: 
~https://github.com/ewlu/gcc-precommit-ci/actions/runs/11389822472~
~https://github.com/ewlu/gcc-precommit-ci/actions/runs/11390176809~
~https://github.com/ewlu/gcc-precommit-ci/actions/runs/11390582485~
https://github.com/ewlu/gcc-precommit-ci/actions/runs/11390649510
=> create gist and preview output on build failures

test/allowlist/gcc/newlib.log
https://github.com/gcc-mirror/gcc/commit/f9f599a44e3156a5f5679adc048ec6ff2f44cc0e fixes
https://github.com/patrick-rivos/gcc-postcommit-ci/issues/1593
=> Remove fixed failures
