.github/workflows/run_checks.yaml

Useful when a patch a fails to apply to baseline, since we don't share that directly with users. As a CI maintainer I'd like to confirm that the baseline failure is real.

Echo failing patches to debug log

---

.github/workflows/build-target.yaml

fixes missing comment id when passing in argument -iid. (looks like `<num>#issue-` instead of `<num>#issue-<cid>`) https://github.com/ewlu/gcc-precommit-ci/actions/runs/6580935069/job/17880493262#step:7:73

fix incorrect reference for comment id in report

---

.github/workflows/lint.yaml

https://github.com/ewlu/gcc-precommit-ci/issues/396#issuecomment-1773124055 does not display the correct markdown for how to find logs

escape tag <patch_name> when generating markdown

---

.github/workflows/build-target.yaml
.github/workflows/call-patchworks-api.yaml
.github/workflows/generate-precommit-summary.yaml
.github/workflows/lint.yaml
.github/workflows/run_checks.yaml
.github/workflows/test-regression.yaml

Depends on https://github.com/patrick-rivos/riscv-gnu-toolchain/pull/442. Allows us to error out on nasty bugs like this one where we forget the `if`:
https://github.com/ewlu/gcc-precommit-ci/blob/fc7001f0f2ecfed69990473d1ff2e0585531622c/.github/workflows/lint.yaml#L64

Pass event to post_check_to_patchworks.py

---

.github/workflows/test-regression.yaml

fixes the baseline hash reporting as seen in https://github.com/ewlu/gcc-precommit-ci/issues/449#issuecomment-1776520951

use build only hash in build reporting on build only

---

.github/workflows/run_checks.yaml
.github/workflows/test-regression.yaml

Resolves #477 where is misinterprets the first part of the email as a separate patch.
https://github.com/ewlu/gcc-precommit-ci/actions/runs/6658976049/job/18097747516#step:9:30

Ignore empty commits when applying

---

.github/workflows/run_checks.yaml

This produced outputs like this:
```
diff --cc gcc/testsuite/lib/target-supports.exp
index 81330c4ba55,af0bf0c48d7..00000000000
--- a/gcc/testsuite/lib/target-supports.exp
+++ b/gcc/testsuite/lib/target-supports.exp
@@@ -2111,16 -2063,16 +2122,29 @@@ proc add_options_for_riscv_zfh { flags 
return "$flags -march=[riscv_get_arch]_zfh"
}
++<<<<<<< HEAD
+proc add_options_for_riscv_zvfh { flags } {
+    if { [lsearch $flags -march=*] >= 0 } {
+	# If there are multiple -march flags, we have to adjust all of them.
+	set flags [regsub -all -- {(?:^|[[:space:]])-march=[[:alnum:]_.]*} $flags &_zvfh ]
+	return [regsub -all -- {((?:^|[[:space:]])-march=[[:alnum:]_.]*_zvfh[[:alnum:]_.]*)_zvfh} $flags \\1 ]
+    }
+    if { [check_effective_target_riscv_zvfh] } {
+	return "$flags"
+    }
+    return …
```

Output diff for fails-to-apply

---

.github/actions/common/build-target/action.yaml

Turns out the github runners don't have the same shell as me ;)
The build log with all output only contains stderr. This PR should fix that.

Tee stdout to build log

---

.github/workflows/generate-precommit-summary.yaml

https://github.com/ewlu/gcc-precommit-ci/actions/runs/9163548707/job/25203037849#step:19:52
By default, `separate_multilib_results.py` will generate multiple files postfixed with `-multilib-report.log` if the originating file was a multilib. Since we build `imc_zba_zbb_zbc_zbs` as a singlelib in precommit, `separate_multilib_results.py` will keep that naming scheme i.e. postfix with `-non-multilib-report.log`. Therefore, when comparing, we had
`current_logs/gcc-newlib-rv32imc_zba_zbb_zbc_zbs-ilp32d-<applied_hash>-non-multilib-report.log` and
`previous_logs/gcc-newlib-rv32imc_zba_zbb_zbc_zbs-ilp32d-<baseline_hash>-multilib-report.log`. Thus `no-baseline` was found.
Rename the file in current_logs to be `multilib` instead of `non-multilib` to make things consistent

rename uc log name to match expected when comparing

---

test/allowlist/gcc/common.log

Jeff mentioned in an email that this timeout was common on his CI too. Interestingly this wasn't an issue until the new runners were added.

Ignore long_branch timeout

---

.github/workflows/generate-precommit-summary.yaml
.github/workflows/init-submodules.yaml

This didn't add/resolve any failures for postcommit so it should have no effect on precommit failures either.

Bump binutils to 5/28 tip-of-tree

---

.github/workflows/generate-precommit-summary.yaml

Reverts ewlu/gcc-precommit-ci#1596
Now that we aren't running duplicates on postcommit:
https://github.com/patrick-rivos/gcc-postcommit-ci/pull/1098
the extraneous resolved-failures won't show up.

Fix typo that caused a no-baseline for non-atomic newlib target

---

.github/workflows/downtime-runner.yaml

The downtime runner reports failures when it fails to find any missed patches to run https://github.com/ewlu/gcc-precommit-ci/actions/runs/9410820797/job/25923111889#step:7:211
It appears to run fine when there are patches that were missed https://github.com/ewlu/gcc-precommit-ci/actions/runs/9433404654

prevent failures from not finding files

---

.github/actions/common/download-build-log-artifact/action.yaml
.github/actions/common/unzip-all-zips/action.yaml
.github/actions/download-all-build-log-artifacts/action.yaml
.github/workflows/patchworks.yaml

This pull request adds a new job to the CI pipeline that runs after the patch_matrix job. The new job aggregates build logs and compares them with the baseline post-commit build log.
The pre-commit option for the parse_new_build_warnings script compares all patch series-target combinations from pre-commit builds with the target from post-commit builds. It shows new build warnings at the target granularity level.
Currently, only 4 targets that can be directly compared between pre-commit and post-commit are used
- linux-rv32gc_zba_zbb_zbc_zbs-ilp32d-non-multilib
- linux-rv64gc_zba_zbb_zbc_zbs-lp64d-non-multilib
After a discussion, the following targets require multilib support due to different targets between post-commit and pre-commit
- linux-rv64gcv-lp64d-multilib
- …

Parse new build warnings Integration

---

test/allowlist/gcc/common.log
test/allowlist/gcc/glibc.rv64.zbs.log

Seen here:
https://github.com/ewlu/gcc-precommit-ci/issues/2030
and a few other places. Seems to affect every target.

Add flaky gfortran/sizeof_6.f90 to allowlist

---

.github/actions/common/build-target/action.yaml

Should fix the annoying double-zip. Will need to do elsewhere but no scripts consumes the build logs currently so that makes this an easy fix.

Remove zip nesting for build log

---

.github/actions/common/build-target/action.yaml
.github/actions/common/run-testsuite/action.yaml
.github/actions/extract-apply-patches-trunk-or-baseline/action.yaml
.github/workflows/downtime-runner.yaml
.github/workflows/generate-precommit-summary.yaml
.github/workflows/lint.yaml
.github/workflows/patchworks.yaml
.github/workflows/run-checks.yaml

This'll probably break but it's a step in the right direction. We can handle postcommit later.

Remove double-zip instances

---

.github/actions/common/build-target/action.yaml

Apply the same changes as https://github.com/patrick-rivos/gcc-postcommit-ci/pull/1864.

Build Log Concurrency Fix

---

.github/workflows/patchworks.yaml

scheduled runs were marked as failure since `rm patch_urls/$base` returned non-zero status code as no patches were found. If there were no riscv patches in that batch, it would still error since the search through the riscv folder would cause error

add debugging statements and also prevent patch removal from failing if no patches are found

---

.github/workflows/patchworks.yaml

if there were no riscv patches but non-riscv non riscv patches were found, the empty directory would mess with the file removal process. essentially, the 
```
for file in riscv_patch_urls/*; do
base=$(basename $file)
```
would result in `base == *`. This, in conjunction with the `sed` statements would strip the list of quotations. Therefore, when parsing the list of patch names with `fromJSON()`, a parsing error occurs since the list is no longer a json string list.
Add additional check to only perform the removal actions if riscv patches were found

add empty dir check

---

.github/workflows/patchworks.yaml

https://github.com/ewlu/gcc-precommit-ci/actions/runs/12399167844/job/34613508992#step:8:239
`[` was being treated as a special character instead of being the target of the pattern match. Since `,]` was being accepted as a valid pattern match, I assumed `[,` would be as well but forgot `[...]` is a valid regex construct. As a result, `sed` would error when the non-riscv patch list was empty.
```
(venv) ewlu@ewlu:/scratch/ewlu/ci/riscv-gnu-toolchain$ cat test.txt
['42125-vect_Do_not_use_partial_vectors_when_emulating_vectors_PR116351-1']
(venv) ewlu@ewlu:/scratch/ewlu/ci/riscv-gnu-toolchain$ echo $base
42125-vect_Do_not_use_partial_vectors_when_emulating_vectors_PR116351-1
(venv) ewlu@ewlu:/scratch/ewlu/ci/riscv-gnu-toolchain$ cat test.txt | sed "s/\s*'$base'\s*//g" | sed "s/,,/,/g" | sed …
```

fix sed command
